server:
  port: 0

spring:
  application:
    name: app-service
  profiles:
    active: dev

## EUREKA ##
eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 2
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/



