
## h2 console ##
spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    username: root
    password: pass
    url: jdbc:h2:tcp://localhost:9092/mem:catalog
## Hibernate ##
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true



