
## OpenFeign ##
spring:
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 3000
            readTimeout: 3000 # 3 sec wait
            loggerLevel: FULL
## Additional yaml cfgs ##
    config:
      name: circuitbreaker